[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.39.0", features = ["full"] }
thiserror = "1.0"